### ISSUE TITLE
too complicated to use, too complicated code

### ISSUE THREAD

**Issue by Dieterbe** [raintank/fakemetrics#1]
fakemetrics tries to support a few different use cases / mechanisms
- realtime load at a fixed rate
- sped-up backfill of historical data (using fewer different series otherwise the volume would be too high)
- varying amounts of organisations and metrics per org
- configurable flushInterval (independent of total rate. rate is computed by `orgs * metrics-per-org / metricPeriod` and by tweaking the flushinterval we recalculate how many we should send per flush)

it tries to do all this with essentially the same code, and the same premade in-memory structures, but using a bunch of different parameters that affect the algorithm. and some of the parameters depend on each other. like metricPeriod must divide without remainder by flushInterval. and then there is runMultiplied and runDivided because we needed a different algorithm and to explain why i have to study https://github.com/raintank/fakemetrics/blob/master/fakemetrics.go#L161-L176  which again proves this stuff is way too complicated and should be simplified

so what we should do:
- implement each use case as its own module, only reusing what makes sense (see the included independent-agents program which just implements 1 mode, but this should become a mode instead of a separate program). then we can invoke desired modes like `fakemetrics backfill` or `fakemetrics agents` or `fakemetrics fixed` instead of figuring out which combination of all the parameters we need
- try to remove options, or at least restrict them to only the modes in which they make sense (such as speedup is only for backfills)

this way we can just add new modes as new needs arise, and we should just document them so it's immediately clear exactly how they behave.

**Comment by OOM-Killer** [comment]
@Dieterbe I've been looking at this today and I'm experimenting with a very early prototype.

I had the following idea: 
In order to get as much flexibility and extendibility as possible I'll not only write modules that correspond a mode, I'll break them up into module types where the types are `timer`, `data generator` and `output`. 

The job of the `timer` is to provide the interval timer and provide the time of a metric, the job of the `data generator` is to provide a metric, the job of the `output` is to connect to an interface and send the metrics there. There can always only be one `timer` and one `data generator`, but there can be one or many `outputs`.

This is my very early and unfinished experiment, the outputs are not implemented yet and I think I should get rid of some duplication in the factories:

https://github.com/OOM-Killer/fakemetrics_ng

This has the advantage that we can cross combine different `data generators`, `outputs` and `timers` more flexibly. It has the disadvantage that the configuration is too complex to do it via cli arguments, so I added a `.ini` file.

What do you think about that? If you think it's unnecessarily complex or just doesn't make any sense then I can also drop it and just create modules that correspond a mode.

**Comment by Dieterbe** [comment]
i probably didn't do a good enough job describing what i want to achieve ultimately.
i want to able to have a set of different workload patterns. let me come up with a bunch below.   fakemetrics_ng currently seems to have some assumptionns such as 1 clock .  maybe with some further changes the modular approach will prove good for composing these different modes.
- independent agents that send data at the same interval, but random offsets (currently implemented as separate independent-agents program in this repo)
- ditto, but where agents are gradually increased over time (similar to [haggar](https://github.com/gorsuch/haggar))
- consistent ingest (with every flush the exact same amount of data)
- backfill mode: for 2 reasons:
  - filling up MT's memory buffers with e.g. 3hours of past data
  - saving a years worth of data to test out rollups
  - I can imagine in the future backfill mode can also be useful for the indepent agents use case when we want to test the effects of different offsets on rollups and consolidation. so maybe this should be listed under crossconcerns

cross-concerns: these are concerns that seem to apply to most/all of the different modes above
- changing keys: points per second rates aside, it should be controllable how many times series keys are used and how many new series names are adopted. in the extreme case there's only ever 1 point for a given series name
- different classes of agents running at different intervals (can perhaps be done with multiple fakemetrics processes?). having different "streams" at different clocks will also be useful for the consistent and backfill mode I think.
- connection open/close/reuse behavior. obviously for agents, but also for consistent mode seems useful.

**Comment by OOM-Killer** [comment]
@Dieterbe Over the past few days I worked on some of the above points, so I just wanted to give you a short status update:
- There is now multi agent support, meaning that many worker threads can be created which all work independently of each other.
- It is configurable if the agents should all be started at once, or if the number should increase slowly over time. The speed at which agents get added can also be defined.
- There's a configurable offset which is applied when an agent is launched. For example it's possible to say that `10` agents should start at once, and each should get a random offset between `0` and the `metric interval`. The offsets can also be defined to be distributed evenly between `0` and `metric interval`, so for `10` agents they would get increasing offsets where each increase is `10 / metric interval`.
- There is also a backfill timer. Using that it's possible to start producing data at a date in the past and then generate at maximum speed. Because usually the generation is faster than Metrictank's ingestion speed the `block-on-write` option should be enabled in the `carbon` output, otherwise the output would just skip (and warn) all the data that's generated while the write is blocking.

Next I'll implement a way to make it adopt new time series, instead of sticking to a fixed set of metric names. It's also not possible yet to use multi agent with different classes of agents, at the moment all the agents run with the same config, I still need to come up with a good way to do that.

**Comment by OOM-Killer** [comment]
@Dieterbe I've pushed some more changes to `fakemetrics_ng`. Apart from taking over most of the changes that you've done in your fork I also implemented most of the requirements you listed above. In order to figure out what to focus on next I'd like to go through the requirements listed in your previous post and think about how/if they are satisfied. I also added some more comments to the [configuration file](https://github.com/OOM-Killer/fakemetrics_ng/blob/master/fakemetrics.ini) to make it more understandable .

## Requirements & solutions:

> - independent agents that send data at the same interval, but random offsets (currently implemented as separate independent-agents program in this repo)

Can be done using the `multiagent` configuration. Random or evenly spread offsets can be configured with the `offsets` parameter in the `multiagent` section.

> - ditto, but where agents are gradually increased over time (similar to haggar)

Can be done with the `slow-increase` option in the `multiagent` section.

> - consistent ingest (with every flush the exact same amount of data)

If I understand this requirement right then the combination of the `realtime` timer with the `simple` data generator should do exactly that.

> - backfill mode: for 2 reasons:

There is a `backfill` timer module which can start at a time in the past and then fast forward

> - filling up MT's memory buffers with e.g. 3hours of past data

`backfill` can be configured to start 3 hours ago

> - saving a years worth of data to test out rollups

Should work with `backfill`, although I haven't tested generating such a large amount of data on my tiny VM yet

> - I can imagine in the future backfill mode can also be useful for the indepent agents use case when we want to test the effects of different offsets on rollups and consolidation. so maybe this should be listed under crossconcerns

I'm not entirely sure if I understand this right. What's the relationship between the offsets and rollups/consolidation? Which type of offset do you mean here, is that just the normal interval offset? If it is just the interval offset then this should be possible by combining the `backfill` timer with the `offsets` option in the `multiagent` section, need to test it though.

> - changing keys: points per second rates aside, it should be controllable how many times series keys are used and how many new series names are adopted. in the extreme case there's only ever 1 point for a given series name

Can be done by using the `keychanger` data generator.

> - different classes of agents running at different intervals (can perhaps be done with multiple fakemetrics processes?). having different "streams" at different clocks will also be useful for the consistent and backfill mode I think.

Can be done using the `flexible` timer, it can give different metric intervals to each agent which will then make the data generators generate the data at varying intervals. Although, currently the output buffer would still be written at the same interval by all agents, that output buffer flush interval can just be configured to a very small number so it's close to the smallest common denominator of the different metric intervals.

> - connection open/close/reuse behavior. obviously for agents, but also for consistent mode seems useful.

I have not implemented any intentional closing/reopening yet, shouldn't be hard though.

## Next steps
- At the moment the only existing output is `carbon`. I should add more outputs like `kafka`, `nsq` or `stdout` to that.
- I started writing a small Python script which I'd like to use to create a mock carbon service which can test if `fakemetrics_ng` does what it is supposed to do. The idea is that this mock service can be started with certain expectations like `metrics per time` and if the expectations are not met it throws an error. This could then be used for testing of `fakemetrics_ng`. 
  Alternatively I could also just use the actual latest stable Metrictank to basically do the same `end2end` test like Metrictank has now, but with the intention of testing `fakemetrics_ng`. This would have the disadvantage that certain information could probably not be queried from Metrictank, like for example if the flush interval was exactly as it was supposed to be. What do you think about these two different approaches? Or do you think testing `fakemetrics_ng` is a waste of time because it's not like a "critical" part of the infrastructure?

**Comment by Dieterbe** [comment]
sorry i haven't had time yet to review your work here.  I would caution against going much further if we're not sure yet it's the right way forward. I don't think extensive testing of fakemetrics/fakemetrics-ng is important at this point, if we want to use a mode it's usually pretty obvious if something's wrong because we by definition use it in workflows where we have a critical eye to the numbers in e.g. the metrictank dashboards, and query the data itself as well.
also don't worry about nsq anymore. it's deprecated. we don't use it anymore.

**Comment by OOM-Killer** [comment]
Ok that makes sense. I won't spend more time on the `fakemetrics_ng` test for now
